# Site settings
title: 'Ruby style guide'
description: "Shopify's Ruby style guide"

# Build settings
markdown: redcarpet
sass:
  style: compressed
redcarpet:
  extensions:
    - autolink
    - space_after_headers
